# Generated by Django 5.2.17 on 2026-09-07 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('doctorate', 'دکتری')], max_length=20)),
                ('entry_year', models.PositiveSmallIntegerField(help_text='سال ورود به دانشگاه، به شمسی (مثال: ۱۴۰۲)')),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('is_on_probation', models.BooleanField(default=False, help_text='آیا در نیمسال گذشته مشروط شده\u200cاید؟')),
                ('last_semester_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='معدل نیمسال گذشته (اختیاری)', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
