"""The single place that knows which language model answers, and how to reach it.

Two backends behind one interface: a hosted API for development speed, and
Ollama for the local deployment the project is ultimately delivered on.
Switching is a config change, not a rewrite — the same separation that let the
embedding layer move from PyTorch to Ollama without touching anything upstream.

Temperature is deliberately near zero. The usual recommendation for this model
family is 0.7, tuned for open-ended chat; here the job is to restate what a
regulation says, where invention is the failure mode and reproducibility
matters for evaluation.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# "gemini" while developing, "ollama" for the local deliverable.
BACKEND = os.getenv("LLM_BACKEND", "gemini")

GEMINI_MODEL = "gemini-3.6-flash"
OLLAMA_MODEL = "qwen3:4b-instruct-2507"

TEMPERATURE = 0.1


def _load_env():
    """Read .env without adding a dependency for four lines of parsing."""
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return

    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


def _generate_gemini(system_prompt, user_message):
    from google import genai
    from google.genai import types

    _load_env()
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY not found — check .env")

    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=user_message,
        config=types.GenerateContentConfig(
            system_instruction=system_prompt,
            temperature=TEMPERATURE,
        ),
    )
    return response.text


def _generate_ollama(system_prompt, user_message):
    import ollama

    response = ollama.chat(
        model=OLLAMA_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        options={"temperature": TEMPERATURE},
    )
    return response["message"]["content"]


def generate(system_prompt, user_message, backend=None):
    """Send a prompt to whichever backend is configured."""
    chosen = backend or BACKEND

    if chosen == "gemini":
        return _generate_gemini(system_prompt, user_message)
    if chosen == "ollama":
        return _generate_ollama(system_prompt, user_message)

    raise ValueError(f"unknown backend: {chosen}")


def active_backend():
    """What the answer will actually be generated by, for logging and reports."""
    return {
        "gemini": f"gemini / {GEMINI_MODEL}",
        "ollama": f"ollama / {OLLAMA_MODEL}",
    }.get(BACKEND, BACKEND)